version: "3.8"

services:
  mongodb:
    image: mongo:6.0  # You can change the version as needed
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - agent-network

  postgres:
    image: postgres:15 
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/pgdata
    networks:
      - agent-network

volumes:
  mongo-data:
  pg-data:

networks:
  agent-network:
    driver: bridge


# docker compose -f docker-compose-infra.yml up --build
# docker compose -f docker-compose-infra.yml down

